"""initial_database_setup

Revision ID: 30d7e0f8b632
Revises: f5bc91121326
Create Date: 2026-07-13 20:13:31.222978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d7e0f8b632'
down_revision: Union[str, Sequence[str], None] = 'f5bc91121326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_organizations_owner_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_owner_id'), ['owner_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("department IS NULL OR department IN ('hr', 'inventory', 'sales')", name=op.f('ck_users_ck_users_valid_department')),
    sa.CheckConstraint("role IS NULL OR role IN ('owner', 'admin', 'hr_manager', 'inventory_manager', 'sales_manager', 'employee')", name=op.f('ck_users_ck_users_valid_role')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("module IN ('inventory','sales','hr','auth','reporting','system')", name=op.f('ck_activity_logs_ck_activity_logs_valid_module')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_activity_logs_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_limit >= 0', name=op.f('ck_customers_ck_customers_credit_limit_non_negative')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_customers_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_org_id'), ['org_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='fk_departments_manager_id_users', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_departments_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('org_id', 'name', name='uq_departments_org_id_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_org_id'), ['org_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('profile_photo_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','resigned')", name=op.f('ck_employees_ck_employees_valid_status')),
    sa.CheckConstraint('salary >= 0', name=op.f('ck_employees_ck_employees_salary_non_negative')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_employees_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('email', name=op.f('uq_employees_email')),
    sa.UniqueConstraint('employee_number', name=op.f('uq_employees_employee_number'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_org_id'), ['org_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_product_categories_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('org_id', 'name', name='uq_product_categories_org_id_name')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_org_id'), ['org_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_suppliers_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_org_id'), ['org_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.Time(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('present','absent','late','leave','holiday')", name=op.f('ck_attendance_ck_attendance_valid_status')),
    sa.CheckConstraint('check_out_time IS NULL OR check_in_time IS NULL OR check_out_time > check_in_time', name=op.f('ck_attendance_ck_attendance_checkout_after_checkin')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_attendance_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_id_attendance_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_org_id'), ['org_id'], unique=False)

    op.create_table('employee_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('cv','contract','national_id','passport','other')", name=op.f('ck_employee_attachments_ck_employee_attachments_valid_type')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_attachments_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_employee_attachments_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_attachments'))
    )
    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_attachments_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('leave_type', sa.String(length=15), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("leave_type IN ('annual','sick','unpaid','emergency','maternity','paternity')", name=op.f('ck_leave_requests_ck_leave_requests_valid_type')),
    sa.CheckConstraint("status IN ('pending','approved','rejected','cancelled')", name=op.f('ck_leave_requests_ck_leave_requests_valid_status')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_leave_requests_ck_leave_requests_dates_logical')),
    sa.CheckConstraint('total_days > 0', name=op.f('ck_leave_requests_ck_leave_requests_days_positive')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_leave_requests_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)

    op.create_table('payroll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('days_worked', sa.Integer(), server_default=sa.text('false'), nullable=False),
    sa.Column('absences', sa.Integer(), server_default=sa.text('false'), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=1), server_default=sa.text('false'), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=12, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','paid','cancelled')", name=op.f('ck_payroll_ck_payroll_valid_status')),
    sa.CheckConstraint('absences   >= 0', name=op.f('ck_payroll_ck_payroll_absences_non_negative')),
    sa.CheckConstraint('allowance >= 0', name=op.f('ck_payroll_ck_payroll_allowance_non_negative')),
    sa.CheckConstraint('bonus    >= 0', name=op.f('ck_payroll_ck_payroll_bonus_non_negative')),
    sa.CheckConstraint('days_worked >= 0', name=op.f('ck_payroll_ck_payroll_days_worked_non_negative')),
    sa.CheckConstraint('deductions >= 0', name=op.f('ck_payroll_ck_payroll_deductions_non_negative')),
    sa.CheckConstraint('gross_salary >= 0', name=op.f('ck_payroll_ck_payroll_gross_non_negative')),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_payroll_ck_payroll_valid_month')),
    sa.CheckConstraint('net_salary  >= 0', name=op.f('ck_payroll_ck_payroll_net_non_negative')),
    sa.CheckConstraint('overtime_hours >= 0', name=op.f('ck_payroll_ck_payroll_overtime_hours_non_negative')),
    sa.CheckConstraint('year  > 2000', name=op.f('ck_payroll_ck_payroll_valid_year')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_payroll_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll')),
    sa.UniqueConstraint('employee_id', 'month', 'year', name='uq_payroll_employee_month_year')
    )
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_org_id'), ['org_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_price >= 0', name=op.f('ck_products_ck_products_cost_price_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_products_ck_products_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_products_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('org_id', 'sku', name='uq_products_org_id_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_org_id'), ['org_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','ordered','partially_received','received','cancelled')", name=op.f('ck_purchase_orders_ck_purchase_orders_valid_status')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_purchase_orders_ck_purchase_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_orders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_purchase_orders_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','confirmed','processing','shipped','delivered','cancelled')", name=op.f('ck_sales_orders_ck_sales_orders_valid_status')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_sales_orders_ck_sales_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sales_orders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_orders_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_sales_orders_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_orders'))
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_org_id'), ['org_id'], unique=False)

    op.create_table('inventory_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), server_default=sa.text('false'), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default=sa.text('false'), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_available >= 0', name=op.f('ck_inventory_stock_ck_inventory_stock_available_non_negative')),
    sa.CheckConstraint('quantity_reserved  >= 0', name=op.f('ck_inventory_stock_ck_inventory_stock_reserved_non_negative')),
    sa.CheckConstraint('reorder_threshold  >= 0', name=op.f('ck_inventory_stock_ck_inventory_stock_threshold_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_stock_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_stock'))
    )
    with op.batch_alter_table('inventory_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_stock_product_id'), ['product_id'], unique=True)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), server_default=sa.text('false'), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity_ordered  > 0', name=op.f('ck_purchase_order_items_ck_po_items_quantity_ordered_positive')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_purchase_order_items_ck_po_items_quantity_received_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_purchase_order_items_ck_po_items_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items'))
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected','completed')", name=op.f('ck_returns_ck_returns_valid_status')),
    sa.CheckConstraint('refund_amount >= 0', name=op.f('ck_returns_ck_returns_refund_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], name=op.f('fk_returns_order_id_sales_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_returns_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_returns_processed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_returns'))
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_org_id'), ['org_id'], unique=False)

    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity   > 0', name=op.f('ck_sales_order_items_ck_sales_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price > 0', name=op.f('ck_sales_order_items_ck_sales_order_items_unit_price_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], name=op.f('fk_sales_order_items_order_id_sales_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order_items'))
    )
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=50), nullable=True),
    sa.Column('supplier_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_products_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id', name=op.f('pk_supplier_products'))
    )
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('inspection_status', sa.String(length=10), nullable=True, comment='pass = قابل للبيع, fail = تالف'),
    sa.Column('refund_method', sa.String(length=20), nullable=True, comment='cash, bank_transfer, credit_note, replace'),
    sa.CheckConstraint("inspection_status IS NULL OR inspection_status IN ('pass','fail')", name=op.f('ck_return_items_ck_return_items_inspection_status')),
    sa.CheckConstraint("refund_method IS NULL OR refund_method IN ('cash','bank_transfer','credit_note','replace')", name=op.f('ck_return_items_ck_return_items_refund_method')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_return_items_ck_return_items_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_return_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('fk_return_items_return_id_returns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_items'))
    )
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_items_return_id'), ['return_id'], unique=False)



    op.create_foreign_key(
    'fk_organizations_owner_id',
    source_table='organizations',
    referent_table='users',
    local_cols=['owner_id'],
    remote_cols=['id'],
    ondelete='RESTRICT'
    )
    # ### end Alembic commands ###






def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_items_return_id'))

    op.drop_table('return_items')
    op.drop_table('supplier_products')
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_items_order_id'))

    op.drop_table('sales_order_items')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_org_id'))
        batch_op.drop_index(batch_op.f('ix_returns_order_id'))

    op.drop_table('returns')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_order_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('inventory_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_stock_product_id'))

    op.drop_table('inventory_stock')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_org_id'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_customer_id'))

    op.drop_table('sales_orders')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_org_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_org_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_org_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_employee_id'))

    op.drop_table('payroll')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_attachments_employee_id'))

    op.drop_table('employee_attachments')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_org_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_employee_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_org_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_org_id'))

    op.drop_table('product_categories')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_org_id'))

    op.drop_table('employees')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_org_id'))

    op.drop_table('departments')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_org_id'))

    op.drop_table('customers')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_org_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_owner_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###






