"""add_profile_photo_and_attachments

Revision ID: 90a92f077f41
Revises: a1e687895f28
Create Date: 2026-07-08 14:01:00.139348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a92f077f41'
down_revision: Union[str, Sequence[str], None] = 'a1e687895f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("file_type IN ('cv','contract','national_id','passport','other')", name=op.f('ck_employee_attachments_ck_employee_attachments_valid_type')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_attachments_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_employee_attachments_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_attachments'))
    )
    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_attachments_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_path')

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_attachments_employee_id'))

    op.drop_table('employee_attachments')
    # ### end Alembic commands ###
